### ISSUE TITLE
Rebase the repository on top of the new Adoptium OpenJDK 11 repository

### ISSUE THREAD

**Issue by ebourg** [HotswapProjects/openjdk-jdk11u-dcevm#11]
The DCEVM repository is based on the [AdoptOpenJDK repository](https://github.com/AdoptOpenJDK/openjdk-jdk11u) which mirrored the [OpenJDK 11 Mercurial repository](http://hg.openjdk.java.net/jdk-updates/jdk11u/). The AdopOpenJDK repository is no longer updated, it has been replaced by the new [Adoptium repository](https://github.com/adoptium/jdk11u) which now tracks the [jdk11u mirror on GitHub](https://github.com/openjdk/jdk11u).

The DCEVM patches will have to be rebased on top of the Adoptium repository, maybe using a new repository to avoid mixing two distinct commit history with conflicting tags.

**Comment by skybber** [comment]
Thanks for info, I'll look at it.

**Comment by skybber** [comment]
There is a new branch `dcevm11-jdk-11.0.12-adoptium ` now, rebased dcevm11 on tag `jdk-11.0.12-ga`. Master is equal to adoptium master, old  master is renamed to `master-old-adopt` since adoptium master has different hashes for same commits!

**Comment by ebourg** [comment]
Thank you for the quick update. The branch builds fine in Debian.
